// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: Floor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FloorServiceClient is the client API for FloorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FloorServiceClient interface {
	ListFloors(ctx context.Context, in *ListFloorsRequest, opts ...grpc.CallOption) (*ListFloorsResponse, error)
	JoinFloor(ctx context.Context, in *JoinFloorRequest, opts ...grpc.CallOption) (FloorService_JoinFloorClient, error)
	CreateFloor(ctx context.Context, in *CreateFloorRequest, opts ...grpc.CallOption) (*CreateFloorResponse, error)
}

type floorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFloorServiceClient(cc grpc.ClientConnInterface) FloorServiceClient {
	return &floorServiceClient{cc}
}

func (c *floorServiceClient) ListFloors(ctx context.Context, in *ListFloorsRequest, opts ...grpc.CallOption) (*ListFloorsResponse, error) {
	out := new(ListFloorsResponse)
	err := c.cc.Invoke(ctx, "/muni.FloorService/ListFloors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *floorServiceClient) JoinFloor(ctx context.Context, in *JoinFloorRequest, opts ...grpc.CallOption) (FloorService_JoinFloorClient, error) {
	stream, err := c.cc.NewStream(ctx, &FloorService_ServiceDesc.Streams[0], "/muni.FloorService/JoinFloor", opts...)
	if err != nil {
		return nil, err
	}
	x := &floorServiceJoinFloorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FloorService_JoinFloorClient interface {
	Recv() (*JoinFloorResponse, error)
	grpc.ClientStream
}

type floorServiceJoinFloorClient struct {
	grpc.ClientStream
}

func (x *floorServiceJoinFloorClient) Recv() (*JoinFloorResponse, error) {
	m := new(JoinFloorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *floorServiceClient) CreateFloor(ctx context.Context, in *CreateFloorRequest, opts ...grpc.CallOption) (*CreateFloorResponse, error) {
	out := new(CreateFloorResponse)
	err := c.cc.Invoke(ctx, "/muni.FloorService/CreateFloor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FloorServiceServer is the server API for FloorService service.
// All implementations must embed UnimplementedFloorServiceServer
// for forward compatibility
type FloorServiceServer interface {
	ListFloors(context.Context, *ListFloorsRequest) (*ListFloorsResponse, error)
	JoinFloor(*JoinFloorRequest, FloorService_JoinFloorServer) error
	CreateFloor(context.Context, *CreateFloorRequest) (*CreateFloorResponse, error)
	mustEmbedUnimplementedFloorServiceServer()
}

// UnimplementedFloorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFloorServiceServer struct {
}

func (UnimplementedFloorServiceServer) ListFloors(context.Context, *ListFloorsRequest) (*ListFloorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFloors not implemented")
}
func (UnimplementedFloorServiceServer) JoinFloor(*JoinFloorRequest, FloorService_JoinFloorServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinFloor not implemented")
}
func (UnimplementedFloorServiceServer) CreateFloor(context.Context, *CreateFloorRequest) (*CreateFloorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFloor not implemented")
}
func (UnimplementedFloorServiceServer) mustEmbedUnimplementedFloorServiceServer() {}

// UnsafeFloorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FloorServiceServer will
// result in compilation errors.
type UnsafeFloorServiceServer interface {
	mustEmbedUnimplementedFloorServiceServer()
}

func RegisterFloorServiceServer(s grpc.ServiceRegistrar, srv FloorServiceServer) {
	s.RegisterService(&FloorService_ServiceDesc, srv)
}

func _FloorService_ListFloors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFloorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloorServiceServer).ListFloors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/muni.FloorService/ListFloors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloorServiceServer).ListFloors(ctx, req.(*ListFloorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FloorService_JoinFloor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinFloorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FloorServiceServer).JoinFloor(m, &floorServiceJoinFloorServer{stream})
}

type FloorService_JoinFloorServer interface {
	Send(*JoinFloorResponse) error
	grpc.ServerStream
}

type floorServiceJoinFloorServer struct {
	grpc.ServerStream
}

func (x *floorServiceJoinFloorServer) Send(m *JoinFloorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FloorService_CreateFloor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFloorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloorServiceServer).CreateFloor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/muni.FloorService/CreateFloor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloorServiceServer).CreateFloor(ctx, req.(*CreateFloorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FloorService_ServiceDesc is the grpc.ServiceDesc for FloorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FloorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muni.FloorService",
	HandlerType: (*FloorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFloors",
			Handler:    _FloorService_ListFloors_Handler,
		},
		{
			MethodName: "CreateFloor",
			Handler:    _FloorService_CreateFloor_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinFloor",
			Handler:       _FloorService_JoinFloor_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Floor.proto",
}
