// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: Floor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationMode int32

const (
	AuthenticationMode_None     AuthenticationMode = 0
	AuthenticationMode_Password AuthenticationMode = 1
)

// Enum value maps for AuthenticationMode.
var (
	AuthenticationMode_name = map[int32]string{
		0: "None",
		1: "Password",
	}
	AuthenticationMode_value = map[string]int32{
		"None":     0,
		"Password": 1,
	}
)

func (x AuthenticationMode) Enum() *AuthenticationMode {
	p := new(AuthenticationMode)
	*p = x
	return p
}

func (x AuthenticationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_Floor_proto_enumTypes[0].Descriptor()
}

func (AuthenticationMode) Type() protoreflect.EnumType {
	return &file_Floor_proto_enumTypes[0]
}

func (x AuthenticationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationMode.Descriptor instead.
func (AuthenticationMode) EnumDescriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{0}
}

type ListFloorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFloorsRequest) Reset() {
	*x = ListFloorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFloorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFloorsRequest) ProtoMessage() {}

func (x *ListFloorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFloorsRequest.ProtoReflect.Descriptor instead.
func (*ListFloorsRequest) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{0}
}

type ListFloorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Floors []*Floor `protobuf:"bytes,1,rep,name=floors,proto3" json:"floors,omitempty"`
}

func (x *ListFloorsResponse) Reset() {
	*x = ListFloorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFloorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFloorsResponse) ProtoMessage() {}

func (x *ListFloorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFloorsResponse.ProtoReflect.Descriptor instead.
func (*ListFloorsResponse) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{1}
}

func (x *ListFloorsResponse) GetFloors() []*Floor {
	if x != nil {
		return x.Floors
	}
	return nil
}

type JoinFloorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorId string `protobuf:"bytes,1,opt,name=floor_id,json=floorId,proto3" json:"floor_id,omitempty"`
}

func (x *JoinFloorRequest) Reset() {
	*x = JoinFloorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinFloorRequest) ProtoMessage() {}

func (x *JoinFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinFloorRequest.ProtoReflect.Descriptor instead.
func (*JoinFloorRequest) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{2}
}

func (x *JoinFloorRequest) GetFloorId() string {
	if x != nil {
		return x.FloorId
	}
	return ""
}

type JoinFloorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinFloorResponse) Reset() {
	*x = JoinFloorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinFloorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinFloorResponse) ProtoMessage() {}

func (x *JoinFloorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinFloorResponse.ProtoReflect.Descriptor instead.
func (*JoinFloorResponse) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{3}
}

type Floor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host           *Host              `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Authentication AuthenticationMode `protobuf:"varint,4,opt,name=authentication,proto3,enum=muni.AuthenticationMode" json:"authentication,omitempty"`
}

func (x *Floor) Reset() {
	*x = Floor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Floor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Floor) ProtoMessage() {}

func (x *Floor) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Floor.ProtoReflect.Descriptor instead.
func (*Floor) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{4}
}

func (x *Floor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Floor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Floor) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Floor) GetAuthentication() AuthenticationMode {
	if x != nil {
		return x.Authentication
	}
	return AuthenticationMode_None
}

type Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Host) Reset() {
	*x = Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{5}
}

func (x *Host) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_Floor_proto protoreflect.FileDescriptor

var file_Floor_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x75, 0x6e, 0x69, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x06, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x06, 0x66, 0x6c, 0x6f,
	0x6f, 0x72, 0x73, 0x22, 0x2d, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x6c, 0x6f, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x6f, 0x72,
	0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x4a, 0x6f, 0x69, 0x6e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x6f,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x2a, 0x2c, 0x0a, 0x12, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x10,
	0x01, 0x32, 0x91, 0x01, 0x0a, 0x0c, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73,
	0x12, 0x17, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x75, 0x6e, 0x69,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x46, 0x6c, 0x6f,
	0x6f, 0x72, 0x12, 0x16, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x46, 0x6c,
	0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x75, 0x6e,
	0x69, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x4e, 0x65, 0x70, 0x68, 0x79, 0x2f, 0x6d,
	0x75, 0x6e, 0x69, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Floor_proto_rawDescOnce sync.Once
	file_Floor_proto_rawDescData = file_Floor_proto_rawDesc
)

func file_Floor_proto_rawDescGZIP() []byte {
	file_Floor_proto_rawDescOnce.Do(func() {
		file_Floor_proto_rawDescData = protoimpl.X.CompressGZIP(file_Floor_proto_rawDescData)
	})
	return file_Floor_proto_rawDescData
}

var file_Floor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Floor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Floor_proto_goTypes = []interface{}{
	(AuthenticationMode)(0),    // 0: muni.AuthenticationMode
	(*ListFloorsRequest)(nil),  // 1: muni.ListFloorsRequest
	(*ListFloorsResponse)(nil), // 2: muni.ListFloorsResponse
	(*JoinFloorRequest)(nil),   // 3: muni.JoinFloorRequest
	(*JoinFloorResponse)(nil),  // 4: muni.JoinFloorResponse
	(*Floor)(nil),              // 5: muni.Floor
	(*Host)(nil),               // 6: muni.Host
}
var file_Floor_proto_depIdxs = []int32{
	5, // 0: muni.ListFloorsResponse.floors:type_name -> muni.Floor
	6, // 1: muni.Floor.host:type_name -> muni.Host
	0, // 2: muni.Floor.authentication:type_name -> muni.AuthenticationMode
	1, // 3: muni.FloorService.ListFloors:input_type -> muni.ListFloorsRequest
	3, // 4: muni.FloorService.JoinFloor:input_type -> muni.JoinFloorRequest
	2, // 5: muni.FloorService.ListFloors:output_type -> muni.ListFloorsResponse
	4, // 6: muni.FloorService.JoinFloor:output_type -> muni.JoinFloorResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Floor_proto_init() }
func file_Floor_proto_init() {
	if File_Floor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Floor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFloorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFloorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinFloorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinFloorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Floor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Floor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Floor_proto_goTypes,
		DependencyIndexes: file_Floor_proto_depIdxs,
		EnumInfos:         file_Floor_proto_enumTypes,
		MessageInfos:      file_Floor_proto_msgTypes,
	}.Build()
	File_Floor_proto = out.File
	file_Floor_proto_rawDesc = nil
	file_Floor_proto_goTypes = nil
	file_Floor_proto_depIdxs = nil
}
