// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: Floor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoType int32

const (
	VideoType_Html5   VideoType = 0
	VideoType_YouTube VideoType = 1
	VideoType_Vimeo   VideoType = 2
)

// Enum value maps for VideoType.
var (
	VideoType_name = map[int32]string{
		0: "Html5",
		1: "YouTube",
		2: "Vimeo",
	}
	VideoType_value = map[string]int32{
		"Html5":   0,
		"YouTube": 1,
		"Vimeo":   2,
	}
)

func (x VideoType) Enum() *VideoType {
	p := new(VideoType)
	*p = x
	return p
}

func (x VideoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoType) Descriptor() protoreflect.EnumDescriptor {
	return file_Floor_proto_enumTypes[0].Descriptor()
}

func (VideoType) Type() protoreflect.EnumType {
	return &file_Floor_proto_enumTypes[0]
}

func (x VideoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoType.Descriptor instead.
func (VideoType) EnumDescriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{0}
}

type Authentication_Mode int32

const (
	Authentication_None     Authentication_Mode = 0
	Authentication_Password Authentication_Mode = 1
)

// Enum value maps for Authentication_Mode.
var (
	Authentication_Mode_name = map[int32]string{
		0: "None",
		1: "Password",
	}
	Authentication_Mode_value = map[string]int32{
		"None":     0,
		"Password": 1,
	}
)

func (x Authentication_Mode) Enum() *Authentication_Mode {
	p := new(Authentication_Mode)
	*p = x
	return p
}

func (x Authentication_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Authentication_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_Floor_proto_enumTypes[1].Descriptor()
}

func (Authentication_Mode) Type() protoreflect.EnumType {
	return &file_Floor_proto_enumTypes[1]
}

func (x Authentication_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Authentication_Mode.Descriptor instead.
func (Authentication_Mode) EnumDescriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{9, 0}
}

type ListFloorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFloorsRequest) Reset() {
	*x = ListFloorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFloorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFloorsRequest) ProtoMessage() {}

func (x *ListFloorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFloorsRequest.ProtoReflect.Descriptor instead.
func (*ListFloorsRequest) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{0}
}

type ListFloorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Floors []*Floor `protobuf:"bytes,1,rep,name=floors,proto3" json:"floors,omitempty"`
}

func (x *ListFloorsResponse) Reset() {
	*x = ListFloorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFloorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFloorsResponse) ProtoMessage() {}

func (x *ListFloorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFloorsResponse.ProtoReflect.Descriptor instead.
func (*ListFloorsResponse) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{1}
}

func (x *ListFloorsResponse) GetFloors() []*Floor {
	if x != nil {
		return x.Floors
	}
	return nil
}

type JoinFloorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorId string `protobuf:"bytes,1,opt,name=floor_id,json=floorId,proto3" json:"floor_id,omitempty"`
}

func (x *JoinFloorRequest) Reset() {
	*x = JoinFloorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinFloorRequest) ProtoMessage() {}

func (x *JoinFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinFloorRequest.ProtoReflect.Descriptor instead.
func (*JoinFloorRequest) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{2}
}

func (x *JoinFloorRequest) GetFloorId() string {
	if x != nil {
		return x.FloorId
	}
	return ""
}

type JoinFloorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Video *Video `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
}

func (x *JoinFloorResponse) Reset() {
	*x = JoinFloorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinFloorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinFloorResponse) ProtoMessage() {}

func (x *JoinFloorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinFloorResponse.ProtoReflect.Descriptor instead.
func (*JoinFloorResponse) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{3}
}

func (x *JoinFloorResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type CreateFloorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorName      string          `protobuf:"bytes,1,opt,name=floor_name,json=floorName,proto3" json:"floor_name,omitempty"`
	Host           *Host           `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Authentication *Authentication `protobuf:"bytes,3,opt,name=authentication,proto3" json:"authentication,omitempty"`
}

func (x *CreateFloorRequest) Reset() {
	*x = CreateFloorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFloorRequest) ProtoMessage() {}

func (x *CreateFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFloorRequest.ProtoReflect.Descriptor instead.
func (*CreateFloorRequest) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFloorRequest) GetFloorName() string {
	if x != nil {
		return x.FloorName
	}
	return ""
}

func (x *CreateFloorRequest) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *CreateFloorRequest) GetAuthentication() *Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

type CreateFloorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorId string `protobuf:"bytes,1,opt,name=floor_id,json=floorId,proto3" json:"floor_id,omitempty"`
}

func (x *CreateFloorResponse) Reset() {
	*x = CreateFloorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFloorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFloorResponse) ProtoMessage() {}

func (x *CreateFloorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFloorResponse.ProtoReflect.Descriptor instead.
func (*CreateFloorResponse) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFloorResponse) GetFloorId() string {
	if x != nil {
		return x.FloorId
	}
	return ""
}

type Floor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host           *Host               `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Authentication Authentication_Mode `protobuf:"varint,4,opt,name=authentication,proto3,enum=muni.Authentication_Mode" json:"authentication,omitempty"`
}

func (x *Floor) Reset() {
	*x = Floor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Floor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Floor) ProtoMessage() {}

func (x *Floor) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Floor.ProtoReflect.Descriptor instead.
func (*Floor) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{6}
}

func (x *Floor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Floor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Floor) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Floor) GetAuthentication() Authentication_Mode {
	if x != nil {
		return x.Authentication
	}
	return Authentication_None
}

type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Source:
	//
	//	*Video_Html5Url
	//	*Video_YoutubeId
	//	*Video_VimeoId
	Source isVideo_Source `protobuf_oneof:"source"`
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{7}
}

func (m *Video) GetSource() isVideo_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (x *Video) GetHtml5Url() string {
	if x, ok := x.GetSource().(*Video_Html5Url); ok {
		return x.Html5Url
	}
	return ""
}

func (x *Video) GetYoutubeId() string {
	if x, ok := x.GetSource().(*Video_YoutubeId); ok {
		return x.YoutubeId
	}
	return ""
}

func (x *Video) GetVimeoId() uint32 {
	if x, ok := x.GetSource().(*Video_VimeoId); ok {
		return x.VimeoId
	}
	return 0
}

type isVideo_Source interface {
	isVideo_Source()
}

type Video_Html5Url struct {
	Html5Url string `protobuf:"bytes,1,opt,name=html5_url,json=html5Url,proto3,oneof"`
}

type Video_YoutubeId struct {
	YoutubeId string `protobuf:"bytes,2,opt,name=youtube_id,json=youtubeId,proto3,oneof"`
}

type Video_VimeoId struct {
	VimeoId uint32 `protobuf:"varint,3,opt,name=vimeo_id,json=vimeoId,proto3,oneof"`
}

func (*Video_Html5Url) isVideo_Source() {}

func (*Video_YoutubeId) isVideo_Source() {}

func (*Video_VimeoId) isVideo_Source() {}

type Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Host) Reset() {
	*x = Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{8}
}

func (x *Host) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Authentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode     Authentication_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=muni.Authentication_Mode" json:"mode,omitempty"`
	Password string              `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Floor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_Floor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_Floor_proto_rawDescGZIP(), []int{9}
}

func (x *Authentication) GetMode() Authentication_Mode {
	if x != nil {
		return x.Mode
	}
	return Authentication_None
}

func (x *Authentication) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_Floor_proto protoreflect.FileDescriptor

var file_Floor_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x75, 0x6e, 0x69, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x06, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x06, 0x66, 0x6c, 0x6f,
	0x6f, 0x72, 0x73, 0x22, 0x2d, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x6c, 0x6f, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x6f, 0x72,
	0x49, 0x64, 0x22, 0x36, 0x0a, 0x11, 0x4a, 0x6f, 0x69, 0x6e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x12, 0x3c, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e,
	0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x30,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x49, 0x64,
	0x22, 0x8e, 0x01, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d,
	0x75, 0x6e, 0x69, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x41,
	0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x52, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x6e, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1d, 0x0a, 0x09, 0x68, 0x74,
	0x6d, 0x6c, 0x35, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x08, 0x68, 0x74, 0x6d, 0x6c, 0x35, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0a, 0x79, 0x6f, 0x75,
	0x74, 0x75, 0x62, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x09, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x08, 0x76, 0x69,
	0x6d, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07,
	0x76, 0x69, 0x6d, 0x65, 0x6f, 0x49, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x22, 0x1a, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7b, 0x0a,
	0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2d, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x1e, 0x0a, 0x04, 0x4d, 0x6f,
	0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x10, 0x01, 0x2a, 0x2e, 0x0a, 0x09, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x74, 0x6d, 0x6c, 0x35,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x59, 0x6f, 0x75, 0x54, 0x75, 0x62, 0x65, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x56, 0x69, 0x6d, 0x65, 0x6f, 0x10, 0x02, 0x32, 0xd9, 0x01, 0x0a, 0x0c, 0x46,
	0x6c, 0x6f, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x4c,
	0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x12, 0x17, 0x2e, 0x6d, 0x75, 0x6e, 0x69,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c,
	0x6f, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40,
	0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x16, 0x2e, 0x6d, 0x75,
	0x6e, 0x69, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x46,
	0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x44, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12,
	0x18, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x75, 0x6e, 0x69,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x4e, 0x65, 0x70, 0x68, 0x79, 0x2f,
	0x6d, 0x75, 0x6e, 0x69, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Floor_proto_rawDescOnce sync.Once
	file_Floor_proto_rawDescData = file_Floor_proto_rawDesc
)

func file_Floor_proto_rawDescGZIP() []byte {
	file_Floor_proto_rawDescOnce.Do(func() {
		file_Floor_proto_rawDescData = protoimpl.X.CompressGZIP(file_Floor_proto_rawDescData)
	})
	return file_Floor_proto_rawDescData
}

var file_Floor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Floor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Floor_proto_goTypes = []interface{}{
	(VideoType)(0),              // 0: muni.VideoType
	(Authentication_Mode)(0),    // 1: muni.Authentication.Mode
	(*ListFloorsRequest)(nil),   // 2: muni.ListFloorsRequest
	(*ListFloorsResponse)(nil),  // 3: muni.ListFloorsResponse
	(*JoinFloorRequest)(nil),    // 4: muni.JoinFloorRequest
	(*JoinFloorResponse)(nil),   // 5: muni.JoinFloorResponse
	(*CreateFloorRequest)(nil),  // 6: muni.CreateFloorRequest
	(*CreateFloorResponse)(nil), // 7: muni.CreateFloorResponse
	(*Floor)(nil),               // 8: muni.Floor
	(*Video)(nil),               // 9: muni.Video
	(*Host)(nil),                // 10: muni.Host
	(*Authentication)(nil),      // 11: muni.Authentication
}
var file_Floor_proto_depIdxs = []int32{
	8,  // 0: muni.ListFloorsResponse.floors:type_name -> muni.Floor
	9,  // 1: muni.JoinFloorResponse.video:type_name -> muni.Video
	10, // 2: muni.CreateFloorRequest.host:type_name -> muni.Host
	11, // 3: muni.CreateFloorRequest.authentication:type_name -> muni.Authentication
	10, // 4: muni.Floor.host:type_name -> muni.Host
	1,  // 5: muni.Floor.authentication:type_name -> muni.Authentication.Mode
	1,  // 6: muni.Authentication.mode:type_name -> muni.Authentication.Mode
	2,  // 7: muni.FloorService.ListFloors:input_type -> muni.ListFloorsRequest
	4,  // 8: muni.FloorService.JoinFloor:input_type -> muni.JoinFloorRequest
	6,  // 9: muni.FloorService.CreateFloor:input_type -> muni.CreateFloorRequest
	3,  // 10: muni.FloorService.ListFloors:output_type -> muni.ListFloorsResponse
	5,  // 11: muni.FloorService.JoinFloor:output_type -> muni.JoinFloorResponse
	7,  // 12: muni.FloorService.CreateFloor:output_type -> muni.CreateFloorResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_Floor_proto_init() }
func file_Floor_proto_init() {
	if File_Floor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Floor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFloorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFloorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinFloorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinFloorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFloorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFloorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Floor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Floor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Floor_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Video_Html5Url)(nil),
		(*Video_YoutubeId)(nil),
		(*Video_VimeoId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Floor_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Floor_proto_goTypes,
		DependencyIndexes: file_Floor_proto_depIdxs,
		EnumInfos:         file_Floor_proto_enumTypes,
		MessageInfos:      file_Floor_proto_msgTypes,
	}.Build()
	File_Floor_proto = out.File
	file_Floor_proto_rawDesc = nil
	file_Floor_proto_goTypes = nil
	file_Floor_proto_depIdxs = nil
}
