// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: Vimeo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListVideoVideosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVideoVideosRequest) Reset() {
	*x = ListVideoVideosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Vimeo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVideoVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoVideosRequest) ProtoMessage() {}

func (x *ListVideoVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Vimeo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideoVideosRequest) Descriptor() ([]byte, []int) {
	return file_Vimeo_proto_rawDescGZIP(), []int{0}
}

type ListVideoVideosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*VimeoVideo `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *ListVideoVideosResponse) Reset() {
	*x = ListVideoVideosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Vimeo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVideoVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoVideosResponse) ProtoMessage() {}

func (x *ListVideoVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Vimeo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoVideosResponse.ProtoReflect.Descriptor instead.
func (*ListVideoVideosResponse) Descriptor() ([]byte, []int) {
	return file_Vimeo_proto_rawDescGZIP(), []int{1}
}

func (x *ListVideoVideosResponse) GetVideos() []*VimeoVideo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type VimeoVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title      string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url        string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	PreviewUrl string `protobuf:"bytes,4,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	AuthorName string `protobuf:"bytes,5,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
}

func (x *VimeoVideo) Reset() {
	*x = VimeoVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Vimeo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VimeoVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VimeoVideo) ProtoMessage() {}

func (x *VimeoVideo) ProtoReflect() protoreflect.Message {
	mi := &file_Vimeo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VimeoVideo.ProtoReflect.Descriptor instead.
func (*VimeoVideo) Descriptor() ([]byte, []int) {
	return file_Vimeo_proto_rawDescGZIP(), []int{2}
}

func (x *VimeoVideo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VimeoVideo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VimeoVideo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VimeoVideo) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *VimeoVideo) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

var File_Vimeo_proto protoreflect.FileDescriptor

var file_Vimeo_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x56, 0x69, 0x6d, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x75, 0x6e, 0x69, 0x22, 0x18, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a,
	0x17, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e,
	0x56, 0x69, 0x6d, 0x65, 0x6f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x06, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x0a, 0x56, 0x69, 0x6d, 0x65, 0x6f, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x60, 0x0a,
	0x0c, 0x56, 0x69, 0x6d, 0x65, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a,
	0x0f, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73,
	0x12, 0x1c, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x6c,
	0x61, 0x73, 0x68, 0x4e, 0x65, 0x70, 0x68, 0x79, 0x2f, 0x6d, 0x75, 0x6e, 0x69, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Vimeo_proto_rawDescOnce sync.Once
	file_Vimeo_proto_rawDescData = file_Vimeo_proto_rawDesc
)

func file_Vimeo_proto_rawDescGZIP() []byte {
	file_Vimeo_proto_rawDescOnce.Do(func() {
		file_Vimeo_proto_rawDescData = protoimpl.X.CompressGZIP(file_Vimeo_proto_rawDescData)
	})
	return file_Vimeo_proto_rawDescData
}

var file_Vimeo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Vimeo_proto_goTypes = []interface{}{
	(*ListVideoVideosRequest)(nil),  // 0: muni.ListVideoVideosRequest
	(*ListVideoVideosResponse)(nil), // 1: muni.ListVideoVideosResponse
	(*VimeoVideo)(nil),              // 2: muni.VimeoVideo
}
var file_Vimeo_proto_depIdxs = []int32{
	2, // 0: muni.ListVideoVideosResponse.videos:type_name -> muni.VimeoVideo
	0, // 1: muni.VimeoService.ListVideoVideos:input_type -> muni.ListVideoVideosRequest
	1, // 2: muni.VimeoService.ListVideoVideos:output_type -> muni.ListVideoVideosResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Vimeo_proto_init() }
func file_Vimeo_proto_init() {
	if File_Vimeo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Vimeo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVideoVideosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Vimeo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVideoVideosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Vimeo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VimeoVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Vimeo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Vimeo_proto_goTypes,
		DependencyIndexes: file_Vimeo_proto_depIdxs,
		MessageInfos:      file_Vimeo_proto_msgTypes,
	}.Build()
	File_Vimeo_proto = out.File
	file_Vimeo_proto_rawDesc = nil
	file_Vimeo_proto_goTypes = nil
	file_Vimeo_proto_depIdxs = nil
}
