// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: Vimeo.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VimeoServiceClient is the client API for VimeoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VimeoServiceClient interface {
	ListVideoVideos(ctx context.Context, in *ListVideoVideosRequest, opts ...grpc.CallOption) (*ListVideoVideosResponse, error)
}

type vimeoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVimeoServiceClient(cc grpc.ClientConnInterface) VimeoServiceClient {
	return &vimeoServiceClient{cc}
}

func (c *vimeoServiceClient) ListVideoVideos(ctx context.Context, in *ListVideoVideosRequest, opts ...grpc.CallOption) (*ListVideoVideosResponse, error) {
	out := new(ListVideoVideosResponse)
	err := c.cc.Invoke(ctx, "/muni.VimeoService/ListVideoVideos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VimeoServiceServer is the server API for VimeoService service.
// All implementations must embed UnimplementedVimeoServiceServer
// for forward compatibility
type VimeoServiceServer interface {
	ListVideoVideos(context.Context, *ListVideoVideosRequest) (*ListVideoVideosResponse, error)
	mustEmbedUnimplementedVimeoServiceServer()
}

// UnimplementedVimeoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVimeoServiceServer struct {
}

func (UnimplementedVimeoServiceServer) ListVideoVideos(context.Context, *ListVideoVideosRequest) (*ListVideoVideosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVideoVideos not implemented")
}
func (UnimplementedVimeoServiceServer) mustEmbedUnimplementedVimeoServiceServer() {}

// UnsafeVimeoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VimeoServiceServer will
// result in compilation errors.
type UnsafeVimeoServiceServer interface {
	mustEmbedUnimplementedVimeoServiceServer()
}

func RegisterVimeoServiceServer(s grpc.ServiceRegistrar, srv VimeoServiceServer) {
	s.RegisterService(&VimeoService_ServiceDesc, srv)
}

func _VimeoService_ListVideoVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideoVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VimeoServiceServer).ListVideoVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/muni.VimeoService/ListVideoVideos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VimeoServiceServer).ListVideoVideos(ctx, req.(*ListVideoVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VimeoService_ServiceDesc is the grpc.ServiceDesc for VimeoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VimeoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muni.VimeoService",
	HandlerType: (*VimeoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVideoVideos",
			Handler:    _VimeoService_ListVideoVideos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Vimeo.proto",
}
