// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "Floor.proto" (package "muni", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { FloorService } from "./Floor";
import type { CreateFloorResponse } from "./Floor";
import type { CreateFloorRequest } from "./Floor";
import type { JoinFloorResponse } from "./Floor";
import type { JoinFloorRequest } from "./Floor";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListFloorsResponse } from "./Floor";
import type { ListFloorsRequest } from "./Floor";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service muni.FloorService
 */
export interface IFloorServiceClient {
    /**
     * @generated from protobuf rpc: ListFloors(muni.ListFloorsRequest) returns (muni.ListFloorsResponse);
     */
    listFloors(input: ListFloorsRequest, options?: RpcOptions): UnaryCall<ListFloorsRequest, ListFloorsResponse>;
    /**
     * @generated from protobuf rpc: JoinFloor(muni.JoinFloorRequest) returns (stream muni.JoinFloorResponse);
     */
    joinFloor(input: JoinFloorRequest, options?: RpcOptions): ServerStreamingCall<JoinFloorRequest, JoinFloorResponse>;
    /**
     * @generated from protobuf rpc: CreateFloor(muni.CreateFloorRequest) returns (muni.CreateFloorResponse);
     */
    createFloor(input: CreateFloorRequest, options?: RpcOptions): UnaryCall<CreateFloorRequest, CreateFloorResponse>;
}
/**
 * @generated from protobuf service muni.FloorService
 */
export class FloorServiceClient implements IFloorServiceClient, ServiceInfo {
    typeName = FloorService.typeName;
    methods = FloorService.methods;
    options = FloorService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListFloors(muni.ListFloorsRequest) returns (muni.ListFloorsResponse);
     */
    listFloors(input: ListFloorsRequest, options?: RpcOptions): UnaryCall<ListFloorsRequest, ListFloorsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListFloorsRequest, ListFloorsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: JoinFloor(muni.JoinFloorRequest) returns (stream muni.JoinFloorResponse);
     */
    joinFloor(input: JoinFloorRequest, options?: RpcOptions): ServerStreamingCall<JoinFloorRequest, JoinFloorResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<JoinFloorRequest, JoinFloorResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateFloor(muni.CreateFloorRequest) returns (muni.CreateFloorResponse);
     */
    createFloor(input: CreateFloorRequest, options?: RpcOptions): UnaryCall<CreateFloorRequest, CreateFloorResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateFloorRequest, CreateFloorResponse>("unary", this._transport, method, opt, input);
    }
}
