// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "Floor.proto" (package "muni", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message muni.ListFloorsRequest
 */
export interface ListFloorsRequest {
}
/**
 * @generated from protobuf message muni.ListFloorsResponse
 */
export interface ListFloorsResponse {
    /**
     * @generated from protobuf field: repeated muni.Floor floors = 1;
     */
    floors: Floor[];
}
/**
 * @generated from protobuf message muni.JoinFloorRequest
 */
export interface JoinFloorRequest {
    /**
     * @generated from protobuf field: string floor_id = 1;
     */
    floorId: string;
}
/**
 * @generated from protobuf message muni.JoinFloorResponse
 */
export interface JoinFloorResponse {
}
/**
 * @generated from protobuf message muni.Floor
 */
export interface Floor {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: muni.Host host = 3;
     */
    host?: Host;
    /**
     * @generated from protobuf field: muni.AuthenticationMode authentication = 4;
     */
    authentication: AuthenticationMode;
}
/**
 * @generated from protobuf message muni.Host
 */
export interface Host {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
}
/**
 * @generated from protobuf enum muni.AuthenticationMode
 */
export enum AuthenticationMode {
    /**
     * @generated from protobuf enum value: None = 0;
     */
    None = 0,
    /**
     * @generated from protobuf enum value: Password = 1;
     */
    Password = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class ListFloorsRequest$Type extends MessageType<ListFloorsRequest> {
    constructor() {
        super("muni.ListFloorsRequest", []);
    }
    create(value?: PartialMessage<ListFloorsRequest>): ListFloorsRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ListFloorsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListFloorsRequest): ListFloorsRequest {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ListFloorsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message muni.ListFloorsRequest
 */
export const ListFloorsRequest = new ListFloorsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListFloorsResponse$Type extends MessageType<ListFloorsResponse> {
    constructor() {
        super("muni.ListFloorsResponse", [
            { no: 1, name: "floors", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Floor }
        ]);
    }
    create(value?: PartialMessage<ListFloorsResponse>): ListFloorsResponse {
        const message = { floors: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ListFloorsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListFloorsResponse): ListFloorsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated muni.Floor floors */ 1:
                    message.floors.push(Floor.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListFloorsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated muni.Floor floors = 1; */
        for (let i = 0; i < message.floors.length; i++)
            Floor.internalBinaryWrite(message.floors[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message muni.ListFloorsResponse
 */
export const ListFloorsResponse = new ListFloorsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinFloorRequest$Type extends MessageType<JoinFloorRequest> {
    constructor() {
        super("muni.JoinFloorRequest", [
            { no: 1, name: "floor_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<JoinFloorRequest>): JoinFloorRequest {
        const message = { floorId: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<JoinFloorRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinFloorRequest): JoinFloorRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string floor_id */ 1:
                    message.floorId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinFloorRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string floor_id = 1; */
        if (message.floorId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.floorId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message muni.JoinFloorRequest
 */
export const JoinFloorRequest = new JoinFloorRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinFloorResponse$Type extends MessageType<JoinFloorResponse> {
    constructor() {
        super("muni.JoinFloorResponse", []);
    }
    create(value?: PartialMessage<JoinFloorResponse>): JoinFloorResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<JoinFloorResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinFloorResponse): JoinFloorResponse {
        return target ?? this.create();
    }
    internalBinaryWrite(message: JoinFloorResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message muni.JoinFloorResponse
 */
export const JoinFloorResponse = new JoinFloorResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Floor$Type extends MessageType<Floor> {
    constructor() {
        super("muni.Floor", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "host", kind: "message", T: () => Host },
            { no: 4, name: "authentication", kind: "enum", T: () => ["muni.AuthenticationMode", AuthenticationMode] }
        ]);
    }
    create(value?: PartialMessage<Floor>): Floor {
        const message = { id: "", name: "", authentication: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Floor>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Floor): Floor {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* muni.Host host */ 3:
                    message.host = Host.internalBinaryRead(reader, reader.uint32(), options, message.host);
                    break;
                case /* muni.AuthenticationMode authentication */ 4:
                    message.authentication = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Floor, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* muni.Host host = 3; */
        if (message.host)
            Host.internalBinaryWrite(message.host, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* muni.AuthenticationMode authentication = 4; */
        if (message.authentication !== 0)
            writer.tag(4, WireType.Varint).int32(message.authentication);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message muni.Floor
 */
export const Floor = new Floor$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Host$Type extends MessageType<Host> {
    constructor() {
        super("muni.Host", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Host>): Host {
        const message = { name: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Host>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Host): Host {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Host, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message muni.Host
 */
export const Host = new Host$Type();
/**
 * @generated ServiceType for protobuf service muni.FloorService
 */
export const FloorService = new ServiceType("muni.FloorService", [
    { name: "ListFloors", options: {}, I: ListFloorsRequest, O: ListFloorsResponse },
    { name: "JoinFloor", options: {}, I: JoinFloorRequest, O: JoinFloorResponse }
]);
