/**
 * @fileoverview gRPC-Web generated client stub for muni
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: pb/Room.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as pb_Room_pb from '../pb/Room_pb';


export class RoomServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorListRooms = new grpcWeb.MethodDescriptor(
    '/muni.RoomService/ListRooms',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    pb_Room_pb.ListRoomsResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    pb_Room_pb.ListRoomsResponse.deserializeBinary
  );

  listRooms(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<pb_Room_pb.ListRoomsResponse>;

  listRooms(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: pb_Room_pb.ListRoomsResponse) => void): grpcWeb.ClientReadableStream<pb_Room_pb.ListRoomsResponse>;

  listRooms(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: pb_Room_pb.ListRoomsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/muni.RoomService/ListRooms',
        request,
        metadata || {},
        this.methodDescriptorListRooms,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/muni.RoomService/ListRooms',
    request,
    metadata || {},
    this.methodDescriptorListRooms);
  }

}

