name: 'Build Envoy'

on:
  push:
    paths:
      - 'envoy/**'
    branches-ignore:
      - 'renovate/**'
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/docker-build.yml@master
    with:
      context: envoy
      image-name: ghcr.io/slashnephy/muni-envoy
      image-platforms: linux/amd64,linux/arm64
