name: 'Check Node'

on:
  push:
    branches:
      - 'master'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'push'
    uses: SlashNephy/.github/.github/workflows/yarn-run.yml@master
    permissions:
      contents: 'read'
    with:
      script: 'build'
      working-directory: 'frontend'

  lint:
    uses: SlashNephy/.github/.github/workflows/yarn-lint.yml@master
    permissions:
      contents: 'read'
      pull-requests: 'write'
    with:
      working-directory: 'frontend'

  format:
    if: github.event_name == 'push'
    uses: SlashNephy/.github/.github/workflows/yarn-format.yml@master
    permissions:
      contents: 'write'
    with:
      working-directory: 'frontend'
